#include <Windows.h>
#include <iostream>
#include <map>
#include <vector>
#include <string>
//#include <random>
//#include <cstring>
//#include <cerrno>
#include "ArgumentParser.h"
#include "Globals.h"